version: 2
updates:
  - package-ecosystem: deno
    directories:
      - '/'
      - '/connectors/*'
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
    groups:
      deno-minor-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
      - infra
    groups:
      github-actions:
        patterns:
          - '*'
