workflows:
  - changed-files:
      - any-glob-to-any-file: .github/workflows/*
documentation:
  - changed-files:
      - any-glob-to-any-file: CHANGELOG.md
      - any-glob-to-any-file: '**/README.md'
      - any-glob-to-any-file: .github/workflows/release.yaml
openexchange:
  - openexchange/**
surepass:
  - surepass/**
