# Trivy configuration file
# This file customizes Trivy's behavior for the TundraLibs project

# Global settings
format: sarif
severity: CRITICAL,HIGH,MEDIUM,LOW
exit-code: 0

# File patterns to skip during filesystem scans
skip-files:
  # Test files and fixtures
  - '**/*.test.ts'
  - '**/test/**'
  - '**/tests/**'
  - '**/fixtures/**'
  - '**/testdata/**'

  # Build artifacts and temporary files
  - '**/node_modules/**'
  - '**/coverage/**'
  - '**/.git/**'
  - '**/.vscode/**'
  - '**/.sonarlint/**'
  - '**/deno.lock'
  - '**/test-report.xml'

  # Documentation
  - '**/*.md'
  - '**/LICENSE'

# Directories to skip entirely
skip-dirs:
  - .git
  - .vscode
  - .sonarlint
  - .devcontainer
  - coverage
  - docs
  - node_modules

# Vulnerability database settings
db:
  # Skip DB update in CI (will use cached version)
  skip-update: false

# File type detection
file-patterns:
  # Include TypeScript files for dependency scanning
  - '*.ts'
  - '*.js'
  - '*.json'
  - 'deno.json'
  - 'deno.lock'

# Secret scanning settings
secret:
  # Skip secret scanning for now, can be enabled later with proper config file
  skip-default: true

# Ignore specific vulnerabilities (use with caution)
ignorefile: .trivyignore

# SARIF template for better GitHub integration
sarif-template: |
  {
    "version": "2.1.0",
    "$schema": "https://json.schemastore.org/sarif-2.1.0.json",
    "runs": [
      {
        "tool": {
          "driver": {
            "name": "Trivy",
            "informationUri": "https://github.com/aquasecurity/trivy",
            "rules": []
          }
        },
        "results": []
      }
    ]
  }
