# Configuration for typos spell checker
# See: https://github.com/crate-ci/typos

[default]
# Extend the default identifier list with more technical terms
extend-identifiers = false

[default.extend-words]
# Technical terms and proper nouns
aes = "aes"
api = "api"
apis = "apis"
ascii = "ascii"
auth = "auth"
base64 = "base64"
cdn = "cdn"
cli = "cli"
cors = "cors"
crud = "crud"
csrf = "csrf"
deno = "deno"
dns = "dns"
elasticsearch = "elasticsearch"
gdpr = "gdpr"
graphql = "graphql"
grpc = "grpc"
gui = "gui"
hipaa = "hipaa"
hmac = "hmac"
http = "http"
https = "https"
iso = "iso"
json = "json"
jwt = "jwt"
md5 = "md5"
mongodb = "mongodb"
mysql = "mysql"
nosql = "nosql"
oauth = "oauth"
postgres = "postgres"
postgresql = "postgresql"
redis = "redis"
rest = "rest"
rsa = "rsa"
sdk = "sdk"
sha = "sha"
sql = "sql"
ssh = "ssh"
ssl = "ssl"
tcp = "tcp"
tls = "tls"
udp = "udp"
ui = "ui"
unicode = "unicode"
uri = "uri"
url = "url"
urls = "urls"
utf = "utf"
uuid = "uuid"
ux = "ux"
webhook = "webhook"
webhooks = "webhooks"
websocket = "websocket"
xml = "xml"
xss = "xss"
yaml = "yaml"
yml = "yml"

# Project specific terms
connect = "connect"
connects = "connects"
tundasoft = "tundasoft"
tundra = "tundra"

# Common technical abbreviations
arg = "arg"
args = "args"
async = "async"
await = "await"
config = "config"
configs = "configs"
const = "const"
enum = "enum"
env = "env"
envs = "envs"
func = "func"
impl = "impl"
impls = "impls"
instanceof = "instanceof"
interface = "interface"
namespace = "namespace"
param = "param"
params = "params"
readonly = "readonly"
repo = "repo"
repos = "repos"
struct = "struct"
typeof = "typeof"

[files]
# Extend the default ignore list
extend-exclude = [
  "*.lock",
  "*.log",
  "*.min.js",
  "*.min.css",
  "dist/**",
  "build/**",
  "node_modules/**",
  ".git/**",
  "coverage/**",
  "*.generated.*",
  "*.bundle.*",
  "*.map",
  "deno.lock",
]

[type.deno]
extend-glob = ["*.ts", "*.js", "*.tsx", "*.jsx"]

[type.config]
extend-glob = ["*.json", "*.yml", "*.yaml", "*.toml", "*.ini"]

[type.docs]
extend-glob = ["*.md", "*.mdx", "*.txt", "*.rst"]
