name: "\U0001F41B Bug Report / ✨ Enhancement Request"
description: Report a bug or request an enhancement for existing connects or workflows
title: '[Connect Name] Brief description of the issue'
labels:
  - bug
  - enhancement
body:
  - type: markdown
    attributes:
      value: >
        Thanks for taking the time to fill out this bug report or enhancement
        request!


        Please provide as much detail as possible to help us understand and
        resolve the issue quickly.
  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What type of issue are you reporting?
      options:
        - Bug Report
        - Enhancement Request
      default: 0
    validations:
      required: true
  - type: dropdown
    id: connect-name
    attributes:
      label: Connect Name
      description: Which connect is this issue related to?
      options:
        - Workflows
      default: 0
    validations:
      required: true
  - type: input
    id: connect-version
    attributes:
      label: Connect Version
      description: What version of the connect are you using?
      placeholder: 'e.g., 1.2.3'
    validations:
      required: true
  - type: textarea
    id: issue-description
    attributes:
      label: Issue Description
      description: >
        Please provide a clear and concise description of the issue you're
        experiencing or the enhancement you're requesting.


        For bugs:

        - What did you expect to happen?

        - What actually happened?

        - Steps to reproduce the issue


        For enhancements:

        - What functionality would you like to see?

        - How would this improve the connect?

        - Any specific use cases?
      placeholder: Describe the issue or enhancement request in detail...
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs and Error Messages
      description: >
        If applicable, add any logs, error messages, or stack traces that might
        help identify the issue.

        Please format code/logs using triple backticks (```).
      placeholder: |
        ```
        Paste logs here...
        ```
    validations:
      required: false
  - type: textarea
    id: environment
    attributes:
      label: Environment Information
      description: Please provide information about your environment
      placeholder: |
        - OS: [e.g., macOS 14.0, Ubuntu 22.04, Windows 11]
        - Deno Version: [e.g., 1.40.0]
        - Node.js Version (if applicable): [e.g., 20.10.0]
        - Browser (if applicable): [e.g., Chrome 120.0.0.0]
        - Architecture: [e.g., x64, arm64]
      value: |
        - OS: 
        - Deno Version: 
        - Node.js Version (if applicable): 
        - Browser (if applicable): 
        - Architecture: 
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: |
        Add any other context about the problem here. This could include:
        - Configuration files
        - Related issues or PRs
        - Workarounds you've tried
        - Screenshots (if applicable)
      placeholder: Any additional information that might be helpful...
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: 'By submitting this issue, you agree to follow our Code of Conduct'
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
